#
# TABLE STRUCTURE FOR: messages
#

DROP TABLE IF EXISTS `messages`;

CREATE TABLE `messages` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `from_user_id` int(10) unsigned NOT NULL,
  `to_user_id` int(10) unsigned NOT NULL,
  `body` text COLLATE utf8_unicode_ci NOT NULL,
  `is_important` tinyint(1) DEFAULT NULL,
  `is_delivered` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (1, 0, 0, 'Veniam a maxime in dolores omnis quaerat molestiae. Quia vel aut sunt alias incidunt eos. Sed eos rerum perferendis tenetur. Similique dolores voluptas eos numquam sequi in consequatur laudantium.', 0, 0, '2014-06-14 11:10:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (2, 0, 0, 'Vel laborum aut voluptatem vero tenetur officiis aliquam nisi. Est ut et nesciunt sed. Sit eveniet voluptatem facere eum ullam. Accusamus et unde sed nam.', 0, 1, '1986-03-07 12:20:08');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (3, 0, 0, 'Labore sapiente laborum eos voluptas tenetur nisi et. Similique dolorum incidunt eum aut architecto.', 1, 1, '1989-10-29 10:00:50');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (4, 0, 0, 'Illum ea qui necessitatibus eos omnis neque impedit reiciendis. Molestiae error rerum quaerat et. Commodi eligendi pariatur quia nihil consequatur modi. Atque beatae rem dolorem quaerat est. Officiis cum minima eius culpa accusamus.', 1, 0, '1989-03-15 05:11:48');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (5, 0, 0, 'Natus neque consequatur vitae. Fugit voluptatem architecto ullam consequatur voluptatibus magni ex. Iure eum iste qui odit aut consequuntur consequatur. Aut distinctio sit id dolorem libero repellat corporis.', 1, 0, '2003-03-20 07:39:59');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (6, 0, 0, 'Qui voluptate doloribus distinctio et. Quia soluta modi id corrupti quidem. Ratione distinctio fugiat asperiores nulla. Neque recusandae provident tenetur.', 1, 0, '1979-08-01 06:44:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (7, 0, 0, 'Exercitationem eveniet atque est quam voluptatem. Odio ut voluptatem nesciunt voluptatem suscipit sapiente aspernatur. Similique est consequuntur vel quae labore.', 0, 1, '2009-07-23 15:56:32');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (8, 0, 0, 'Nihil ut nostrum ut id adipisci culpa officiis quos. Totam explicabo ad illum beatae dolores. Voluptates beatae numquam tenetur consequuntur eius et dolorum. Ut fuga et ipsam.', 1, 0, '1982-06-11 05:51:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (9, 0, 0, 'Earum et laboriosam consequatur vitae consectetur amet quisquam. Eos dolore repudiandae harum dicta commodi adipisci nemo. Voluptas hic corporis odio provident possimus aut neque. Officia iure sit omnis eos accusamus quod.', 1, 0, '2004-02-02 06:14:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (10, 0, 0, 'Rerum illo vel dolorem et et et odit est. Dolor officia saepe totam nam labore impedit. Consequatur rem illo facere quos laudantium nam.', 1, 1, '1984-03-12 10:00:24');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (11, 0, 0, 'Culpa eos sint placeat animi recusandae. Ad aut non velit et sit dolor enim. Quis deleniti ad voluptatem laborum vero.', 0, 1, '1989-10-18 16:08:47');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (12, 0, 0, 'Id natus similique omnis quia quaerat. Pariatur corrupti dolorem accusantium officiis suscipit. Doloribus soluta quo sequi et aut odio. Sunt amet aut aspernatur molestiae corrupti autem possimus.', 1, 0, '1977-07-19 05:06:36');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (13, 0, 0, 'Autem laborum unde ad reprehenderit soluta amet. Dolorum doloremque exercitationem qui provident. Reiciendis sint rem eum delectus quo tempore.', 1, 1, '1995-09-03 03:06:49');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (14, 0, 0, 'Officia qui quasi at qui ea. Consequuntur sint incidunt sed rem rerum in. Magni impedit cum quae et ipsam doloremque. Qui vero quia harum laborum voluptate consequatur omnis minus.', 1, 0, '1983-05-21 00:34:30');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (15, 0, 0, 'Molestiae rem unde itaque nobis a qui. Quas error qui fugit deserunt dolorum eos libero. Inventore vitae provident quam qui fugiat perspiciatis.', 0, 0, '2009-03-22 14:32:24');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (16, 0, 0, 'Possimus sit sapiente debitis nam officiis. Molestiae ut provident beatae. Modi et sit inventore et molestiae velit in a.', 0, 1, '1994-05-25 13:31:35');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (17, 0, 0, 'Et quisquam ut placeat voluptatum quia. Alias voluptatem ratione eum aut distinctio sit similique. Quidem sapiente odit sit excepturi aperiam. Corporis omnis voluptas quo blanditiis.', 0, 0, '2019-08-16 20:30:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (18, 0, 0, 'Magni occaecati perspiciatis dolor saepe voluptas laboriosam. Sed unde possimus est. Ut ea hic et ut ab. Facere necessitatibus laborum aliquam in nemo sit veritatis. Temporibus ullam asperiores expedita placeat doloremque non dolore.', 0, 1, '2007-06-13 19:53:46');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (19, 0, 0, 'Expedita natus vero enim corrupti. Aperiam mollitia molestiae quae quis quibusdam. Quis ratione unde eum voluptas cum quia.', 1, 1, '1988-03-08 01:13:13');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (20, 0, 0, 'Minus similique repudiandae quibusdam vero laborum aut. In repudiandae soluta error temporibus atque. Debitis omnis dolorem et quo quo minus ut. Rerum voluptas reprehenderit voluptatem iste ut itaque voluptate. Nobis dicta dolore veritatis aut similique quaerat qui quia.', 0, 0, '2004-01-25 01:52:22');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (21, 0, 0, 'Qui molestias autem magni corrupti. Consequatur veniam totam fugiat consequatur velit. Omnis omnis temporibus nisi fuga dolores cupiditate deleniti.', 1, 1, '1981-01-24 20:43:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (22, 0, 0, 'Velit sit dignissimos quidem nostrum sit. Laboriosam rem repudiandae sit sed dolorum sit eos qui. Quisquam natus et exercitationem ea unde. Quam doloribus est reprehenderit. Error quos vitae reiciendis quibusdam.', 1, 1, '1994-11-17 04:15:19');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (23, 0, 0, 'Labore eos et id eius nesciunt libero est. Assumenda voluptas sint rem quisquam eum alias omnis. Suscipit enim eveniet voluptates odit rem ut quo.', 1, 1, '2001-08-29 10:10:35');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (24, 0, 0, 'Ut officia quasi pariatur aliquam voluptatem ut et. Vitae et est ea ut velit a sequi non. Mollitia minima voluptatibus ut omnis qui. Voluptatem et aut sit pariatur consequatur porro.', 1, 1, '2008-03-08 15:52:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (25, 0, 0, 'Facilis reprehenderit possimus impedit vel est magni. Consequatur dolor rem nisi magni. Totam officia nesciunt porro sit fugit voluptas.', 1, 0, '2007-04-02 16:46:38');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (26, 0, 0, 'Rem recusandae dolorum repudiandae sit perferendis quia et. Autem in dolorem voluptatem non distinctio harum. Qui vel atque consequuntur et voluptatem quos. Fuga assumenda eum esse sed et consequatur.', 0, 0, '2009-10-09 22:40:25');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (27, 0, 0, 'Dicta ullam aut laborum omnis autem vel quia. Repellat voluptates delectus fugiat et id quod. Amet repudiandae dolorum libero quo dolorem. Molestiae voluptas eum facilis.', 0, 0, '2007-07-17 16:16:04');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (28, 0, 0, 'Fuga in aut odit minus est est ipsum hic. Itaque quasi autem quibusdam consequuntur voluptas perspiciatis consequatur. Nulla ut nobis tempore assumenda atque autem qui. Dolor atque animi officiis sed necessitatibus qui.', 1, 0, '2006-12-09 11:52:56');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (29, 0, 0, 'Tenetur et impedit eius qui dolor. Dolores doloribus est ratione neque harum sed velit sit. Excepturi recusandae repellendus aspernatur et. Quasi rem maiores et est.', 0, 1, '1999-06-30 08:53:36');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (30, 0, 0, 'Qui suscipit et itaque accusantium ad nulla soluta. Quos tempora inventore quam corrupti ea qui quisquam. Laudantium aut est praesentium.', 0, 1, '1975-01-09 23:18:12');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (31, 0, 0, 'Nisi est expedita et illum. Vero rerum voluptatum in cum.', 0, 0, '1973-08-06 23:25:34');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (32, 0, 0, 'Omnis consequatur sunt in neque molestiae ut. Nobis nihil et nihil doloribus aut. Pariatur accusantium et temporibus voluptatem ex consequatur.', 0, 1, '2010-10-31 23:10:52');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (33, 0, 0, 'Beatae reiciendis laboriosam dolor adipisci rerum doloremque. Aperiam qui aut doloremque unde natus occaecati.', 1, 0, '2015-08-14 14:47:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (34, 0, 0, 'Vitae unde mollitia autem pariatur animi. Saepe quia nisi similique vero hic. Cupiditate vel odit voluptatem adipisci illum aspernatur quis culpa. Quidem sit qui numquam asperiores sapiente.', 1, 0, '2009-09-10 14:55:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (35, 0, 0, 'Est et ipsum accusamus quis. Aliquam aut animi ea accusamus dolorem sit eaque. Voluptate et ipsum sit doloremque et eos aut. Id dolore amet iste at.', 0, 0, '1971-10-15 07:04:49');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (36, 0, 0, 'Expedita rerum voluptatem fuga magnam praesentium. Et quis corporis necessitatibus commodi aut. Exercitationem ut totam suscipit consequuntur nisi cumque accusantium. Quas deleniti voluptas blanditiis ut optio.', 1, 1, '1973-11-06 21:52:42');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (37, 0, 0, 'Sed illum velit nihil voluptatem modi quisquam amet est. Et vel quis ex consequatur consequatur a. Occaecati quia qui numquam est.', 0, 1, '1970-01-07 12:23:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (38, 0, 0, 'Sunt ut est repellendus quia qui debitis. Sunt necessitatibus ut dolor est error eius cum nulla. Quo aperiam repellat aut quae occaecati aperiam.', 0, 0, '1976-03-13 17:42:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (39, 0, 0, 'Consequatur ad voluptates optio eaque ipsa. Laudantium repellat sed voluptatem nostrum molestiae maiores voluptate. Non consequatur et veniam sint fugiat eligendi. Facere tenetur reiciendis id neque.', 0, 1, '2010-01-30 20:36:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (40, 0, 0, 'Hic quaerat odio eligendi veniam velit. Vel nihil impedit voluptatem earum voluptatum. Sunt qui voluptatem placeat facere.', 0, 1, '1982-06-30 03:29:40');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (41, 0, 0, 'Voluptatem porro nostrum rerum sapiente laborum aperiam. Quaerat qui autem eos voluptatibus. Ut quidem eum ea dicta aut in iusto quod.', 1, 0, '1984-10-04 13:26:30');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (42, 0, 0, 'Nostrum doloremque et et et sed earum voluptatem. Dolores eaque quasi quaerat facilis aspernatur. Sapiente dolorem quam quo voluptatem.', 1, 1, '1998-08-07 04:07:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (43, 0, 0, 'Pariatur reiciendis voluptas qui laborum. Quidem cupiditate quos sit et culpa. Totam quo ut ut voluptates et atque. Magnam nam error a quod cupiditate.', 1, 0, '1993-06-17 21:06:19');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (44, 0, 0, 'Voluptatem assumenda aliquid nulla veritatis architecto consequatur. Aut consectetur quia dolore laborum. Eligendi expedita quas eius saepe deleniti.', 0, 1, '1976-01-21 14:47:52');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (45, 0, 0, 'Et et itaque quam aliquam magnam beatae dolores non. Delectus corrupti voluptas non quo aut voluptates et numquam. Amet sed praesentium sint veniam dolorum velit. Totam et id qui nihil culpa minus delectus sunt.', 0, 0, '1986-05-05 04:00:29');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (46, 0, 0, 'Rerum veritatis voluptatum eveniet reiciendis. Non quia sit quidem adipisci qui quo dolores. Voluptatem ratione deleniti sit voluptas blanditiis. Qui dolor quisquam tempora in voluptatum. Et eum tempore vel et veniam ut.', 1, 0, '1974-03-01 22:04:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (47, 0, 0, 'Sed laboriosam a et adipisci ratione commodi quos rerum. Ea sit et eveniet accusantium et omnis officiis. Dicta velit eveniet nemo rerum quo porro.', 0, 0, '2002-07-18 23:20:32');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (48, 0, 0, 'Aspernatur ad soluta omnis quos. Mollitia a autem quae aut sunt. Tempore id sed nihil.', 0, 1, '1974-04-23 01:09:48');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (49, 0, 0, 'Repellat autem enim est. Omnis nihil voluptatem quod et possimus consequuntur. Molestias doloribus esse quis nisi ipsam ad. Velit sit sequi laboriosam facilis.', 0, 1, '1987-12-23 05:24:41');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (50, 0, 0, 'Qui deleniti magni illo. Rem et eos quibusdam temporibus fuga consequuntur.', 0, 0, '1977-11-14 17:04:57');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (51, 0, 0, 'Rerum accusamus officiis suscipit recusandae. Eligendi quod qui omnis odit voluptatem nihil reprehenderit. Aliquam voluptatem officiis et culpa consequatur. Blanditiis expedita illo et debitis sapiente.', 0, 1, '1985-04-21 13:15:06');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (52, 0, 0, 'Est voluptatibus aliquam distinctio numquam fuga minima quaerat. Omnis quod sed quo dolore et. Consequatur earum necessitatibus enim facere. Magni et saepe repellendus vero ipsam mollitia. Ipsa eligendi quidem sed officiis non.', 1, 0, '1980-07-21 23:44:34');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (53, 0, 0, 'Sint voluptatem doloribus aut voluptatem. Temporibus at deserunt quos suscipit. Consequatur eaque molestias aut est eaque eum reprehenderit.', 1, 0, '1989-10-07 13:03:56');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (54, 0, 0, 'Molestiae et sint aut aperiam voluptas quia velit. Et sunt in aut voluptatum delectus neque nisi. Saepe ea veritatis quos maxime voluptas labore. Autem ipsum qui similique quam accusantium cupiditate perferendis nemo.', 1, 1, '2019-04-10 22:43:33');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (55, 0, 0, 'Magni dolore aspernatur eos praesentium omnis unde ut. Est nemo voluptas qui fugit. Voluptatem quos enim tenetur. Porro eligendi saepe rerum adipisci dolorum deserunt.', 0, 0, '1971-01-12 08:13:40');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (56, 0, 0, 'Expedita est neque ipsa quia excepturi sapiente iusto. Velit quia sed possimus. Enim ipsum qui et quo perferendis aut. Ea ut facere aut illum eum. Nihil sint vel perferendis quaerat iure.', 0, 0, '1975-04-08 21:33:52');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (57, 0, 0, 'Dolorem esse libero laborum et dolor. Aut cupiditate ut corporis corrupti rem rerum est. Vitae ut possimus iste accusantium aspernatur.', 0, 0, '1979-01-08 00:16:38');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (58, 0, 0, 'Modi placeat cupiditate numquam. Optio iusto fuga laboriosam ut neque ut maxime. Autem explicabo placeat ipsam magni est maxime est.', 0, 0, '2005-07-24 18:10:26');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (59, 0, 0, 'Nihil libero et culpa dolores. Natus et voluptas magnam. Mollitia culpa fugiat voluptas voluptatem. Fugiat pariatur non sunt assumenda minima fuga.', 1, 1, '1995-07-15 06:57:31');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (60, 0, 0, 'Distinctio officia tenetur vero velit sed in fugit. Qui consequatur quaerat quis cumque ex. Unde ipsam debitis nulla nihil vel. Est amet architecto facere perferendis.', 0, 0, '1971-05-11 06:58:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (61, 0, 0, 'Perferendis aspernatur nobis libero vel cum unde sed. Voluptatem quaerat recusandae ad expedita. Veritatis ut tempore earum fugiat eius expedita pariatur.', 0, 1, '2000-09-01 14:47:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (62, 0, 0, 'Sit pariatur fugiat sit consequatur ullam nesciunt. Est dolor aspernatur reprehenderit quos magnam voluptas et. Molestias illo dicta maxime et soluta.', 0, 0, '2010-06-02 22:48:13');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (63, 0, 0, 'Qui repellendus adipisci nostrum mollitia tempora in aut. Et est et molestias est dolorum ducimus. Nisi ducimus sed eos eaque. Omnis tempora porro omnis ut ut sit.', 1, 1, '1971-08-16 21:33:30');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (64, 0, 0, 'Provident odit labore iusto molestiae beatae. Sit sed eum facilis maiores ratione. Omnis consequatur modi blanditiis repellat.', 1, 1, '2015-10-23 20:24:54');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (65, 0, 0, 'Laudantium numquam sint et assumenda officia aspernatur sed. Quaerat fugit qui et eligendi necessitatibus odio est. Aut quia a fuga ipsam animi laudantium iusto deleniti.', 1, 0, '1995-05-05 05:01:45');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (66, 0, 0, 'Tempora veniam maiores culpa eos consequatur soluta impedit. Placeat tempore qui veniam vero unde at quas.', 1, 1, '2007-01-18 05:29:14');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (67, 0, 0, 'Dolore labore sed doloremque beatae et. Saepe perspiciatis assumenda est qui unde eveniet ut. Quibusdam excepturi odio repudiandae eveniet.', 0, 1, '1984-04-13 10:20:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (68, 0, 0, 'Vero doloremque non minus dicta autem. Laboriosam qui qui quo doloribus. Suscipit modi optio vitae quis velit. Minus aperiam nisi necessitatibus sed quisquam veniam recusandae omnis.', 1, 0, '1972-07-21 13:56:49');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (69, 0, 0, 'Animi perspiciatis et alias reiciendis. Explicabo voluptates sunt et voluptatem. Commodi quasi itaque ut vel. Asperiores dignissimos eligendi consequuntur dicta omnis beatae et ratione.', 1, 0, '1994-02-09 16:50:01');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (70, 0, 0, 'Voluptatem fuga et vitae ut reprehenderit iure. Accusantium placeat et quia qui. Nisi doloribus beatae autem animi et enim. Esse non autem optio quia.', 1, 1, '1974-09-01 12:44:06');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (71, 0, 0, 'Eveniet voluptas nobis magnam quisquam. Architecto quas odio excepturi quae quam voluptas. Qui laborum ad et nemo placeat eum consequatur omnis.', 0, 1, '1975-08-07 10:19:08');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (72, 0, 0, 'Quia tempora similique voluptates sint ut. Et reprehenderit doloremque provident. Sapiente consequatur velit laborum quaerat. Aut earum illo eaque tempora aliquid omnis.', 1, 0, '1989-09-14 12:15:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (73, 0, 0, 'Enim distinctio dolorem laborum. Quos tenetur ut deserunt ea. Corrupti velit omnis numquam aperiam.', 1, 1, '1971-11-21 09:22:39');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (74, 0, 0, 'Aspernatur nemo id optio totam modi. Praesentium aut error consequatur eum doloremque et est. Dignissimos at a ut quod a deleniti dignissimos repellat. Temporibus doloremque nisi itaque deserunt.', 0, 0, '1971-07-28 07:39:51');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (75, 0, 0, 'Perspiciatis repellat eum voluptatem ducimus asperiores quasi aut delectus. Omnis quo libero nulla suscipit. Sequi autem perspiciatis rerum ut.', 1, 0, '1998-04-03 20:54:27');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (76, 0, 0, 'Commodi officia cumque occaecati optio. Nulla quas quia earum consequatur. Sapiente quam qui veritatis aut nihil ab. Et assumenda veritatis odio accusamus neque laborum sequi ullam.', 1, 1, '2005-05-28 11:17:11');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (77, 0, 0, 'Eligendi excepturi ipsum repellat modi. Veritatis non harum voluptatem corporis sunt. Maiores aliquam illum nihil aut minima aut pariatur.', 0, 0, '2010-01-17 20:55:54');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (78, 0, 0, 'Veniam qui dolore error iusto doloremque. Quis consequatur ab sunt sed corrupti ullam. Quia commodi iste sapiente deleniti modi velit eum. Perferendis possimus consequatur nemo.', 1, 0, '2013-11-28 10:05:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (79, 0, 0, 'Et repellendus quis et sit reprehenderit. Qui autem a eius consequatur harum at aut. Quam beatae iusto explicabo architecto.', 1, 1, '2015-10-15 19:50:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (80, 0, 0, 'Aperiam ut nostrum repellendus aspernatur non dolorem. Ab culpa saepe molestiae in totam. Dolores animi aut tempora et sunt. Totam occaecati distinctio eveniet ullam facilis.', 1, 0, '2007-02-28 06:18:03');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (81, 0, 0, 'Sequi beatae laboriosam exercitationem aut libero vitae. Sint libero et nihil. Molestias eveniet voluptatem ab praesentium.', 1, 1, '2004-05-07 09:47:55');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (82, 0, 0, 'Possimus dicta labore id. Fugit similique illo aut aut. Qui ut et aut debitis.', 1, 0, '1984-06-04 22:57:50');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (83, 0, 0, 'Est ex et minus qui enim et nostrum. Eum voluptatem mollitia sit et unde libero quis. Rerum non sunt optio beatae.', 1, 1, '1976-01-18 01:12:43');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (84, 0, 0, 'Est aut non quasi. Quia eum animi similique illum inventore veritatis eius. Et magni non cumque totam. Est ut et voluptatem perspiciatis.', 0, 1, '2019-05-24 04:36:34');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (85, 0, 0, 'Quod asperiores reiciendis corrupti qui quia. Quaerat quidem nihil odit qui. Velit officia at illum nulla. Ipsam non ratione nulla voluptatem ipsum in.', 0, 1, '2010-08-15 08:57:58');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (86, 0, 0, 'Sunt facilis ratione illo. Tempore et architecto et et velit. Quibusdam rerum quaerat veniam soluta molestiae quasi. Dolorum aliquam nulla atque est.', 1, 0, '1992-03-28 21:22:21');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (87, 0, 0, 'Delectus et officiis labore est. Optio laborum ullam vel et. Omnis molestiae labore culpa voluptatem aperiam velit.', 0, 0, '1982-01-11 00:26:33');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (88, 0, 0, 'Consequuntur cumque eaque est esse provident. Aperiam quis omnis voluptatem vero. Eligendi eos adipisci molestiae minima porro. Quo culpa adipisci quibusdam esse dolore saepe.', 0, 0, '2010-03-22 05:13:38');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (89, 0, 0, 'Quasi suscipit omnis deleniti in. Nesciunt blanditiis dignissimos id occaecati odio maxime. Sapiente dolorem sit tempore aliquam.', 1, 0, '2004-02-04 14:34:56');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (90, 0, 0, 'Atque autem accusamus sit ducimus. Ullam suscipit odio placeat perferendis pariatur qui. Occaecati ea doloribus quisquam excepturi iusto veniam nihil.', 1, 0, '2007-11-24 05:32:07');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (91, 0, 0, 'Aut error et omnis molestiae doloribus. Accusantium sunt non exercitationem ad. Rerum hic ipsum aut vel veniam sint laboriosam.', 0, 0, '1992-08-29 05:28:11');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (92, 0, 0, 'Blanditiis consequatur consequatur sit magnam nesciunt ipsam aspernatur. Eos id enim commodi et. Excepturi iusto et voluptatibus porro ut assumenda.', 1, 1, '2004-06-15 04:54:10');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (93, 0, 0, 'Minima rerum voluptate amet sequi possimus. Quas quas eveniet cum dolorum neque non aut. Qui aliquam veritatis dignissimos magni ullam. Voluptatibus nam sit officiis autem quos nesciunt.', 0, 1, '2017-11-11 01:06:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (94, 0, 0, 'Voluptate non facilis architecto. Molestias dolorum quis ab soluta aspernatur magni quia.', 0, 0, '1981-07-04 04:45:23');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (95, 0, 0, 'Repellat vero eos placeat molestias ullam aut. Provident porro alias et eum fugiat. Est qui voluptas laborum sed.', 1, 0, '2012-01-01 03:39:49');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (96, 0, 0, 'Facere debitis magni asperiores cum. Commodi magnam tenetur consequatur consequuntur vitae omnis. Sunt non quaerat magnam facere ad magni nam. Asperiores repellat vitae aspernatur minus temporibus ex.', 0, 0, '1986-01-25 18:29:20');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (97, 0, 0, 'Dolorum animi odio et dicta laboriosam non optio architecto. Molestias rem perferendis qui porro velit. Voluptate qui libero nulla.', 0, 0, '2003-01-28 16:00:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (98, 0, 0, 'Asperiores laboriosam omnis dolorem ducimus unde quidem non. Et nesciunt et rerum voluptates voluptas. Nam et quis aliquam deleniti fuga molestias molestias.', 0, 0, '1974-01-15 16:43:17');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (99, 0, 0, 'Velit doloribus sapiente fugit quo est. Qui est nihil incidunt eos. Nemo eveniet facilis id qui eum enim. Necessitatibus vel deserunt nemo labore nobis saepe eligendi.', 0, 1, '1980-11-01 14:34:53');
INSERT INTO `messages` (`id`, `from_user_id`, `to_user_id`, `body`, `is_important`, `is_delivered`, `created_at`) VALUES (100, 0, 0, 'Recusandae quia et et et iste voluptatum rerum. Fugit repellat sequi accusantium quis velit. Qui voluptatem quia consectetur sit vel. Rerum quia magni suscipit nihil.', 1, 1, '1998-03-09 09:17:50');


